### PR TITLE
Fix getName() on Android

### LINKED ISSUE #43: getName() returns undefined on Android
**Describe the bug**

Calling `getName()` on Android returns undefined.

This can be tested by adding a call to `getName()` in the example app and observing it does not work.

**To Reproduce**

1. Add a call to `getName()` after example app startup with `alert(name)`.
2. Restart app (optionally setting a custom icon first)
3. Observe alert with undefined

**Expected behavior**

`getName()` should work like iOS

**Smartphone (please complete the following information):**

- Device: Pixel 7a
- OS: Android 13

### PR DESCRIPTION
**Pull request by aeharding**
This fixes #43. The logic I'm using here was inspired from https://github.com/true-hamid/rn-dynamic-app-icon

### CODE REVIEW

File: android/src/main/java/com/mycompany/plugins/example/AppIconBase.java [hunk 1]
```diff
@@ -35,9 +39,11 @@ public Boolean isSupported() {
     }
 
     public String getName() {
-        ComponentName componentName = new ComponentName(this.activity, this.activity.getClass());
+        Intent intent = pm.getLaunchIntentForPackage(context.getPackageName());
+        ComponentName componentName = intent.getComponent();
         int status = pm.getComponentEnabledSetting(componentName);
-        if (status == PackageManager.COMPONENT_ENABLED_STATE_ENABLED) {
+
+        if (status == PackageManager.COMPONENT_ENABLED_STATE_ENABLED || status == PackageManager.COMPONENT_ENABLED_STATE_DEFAULT) {
```
Comment (aeharding) [inline android/src/main/java/com/mycompany/plugins/example/AppIconBase.java:46]: I'm not really sure if this `if()` statement is needed, it's not used in the https://github.com/true-hamid/rn-dynamic-app-icon library.

**Comment by johnborges** [comment]
@aeharding Let me just test this with my AVD and then I'll approve.

**Comment by aeharding** [comment]
@johnborges Any questions with this? Thank you!

**Review by johnborges — APPROVED** [review]
